package.json

Fix dependencies scope between `dependencies` and `devDependencies`.
Also, add missing `npx` command to `compile` script.

Fix dependencies scope

---

.travis.yml
package.json

Setup Travis CI, as the title implies.

Setup Travis CI.

---

.eslintrc
jest.config.js
jest.setup.js
package.json
packages/components/src/Button/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Button/__tests__/index.test.js
packages/core/src/theme-provider/index.js
yarn.lock

This PR aims to improve our test suit.
- Add @testing-library/jest-dom
- Add react-test-renderer
- Add jest-styled-components
- Update React and React DOM version to match react-test-renderer
- Create global renderWithTheme
- Create global rendererCreateWithTheme
- Create global requestAnimationFrame
- Fix Normalize comment on global style to avoid breaking tests
- Update Button base tests

Improve test suit

---

packages/components/README.md
packages/core/README.md
packages/icons/README.md

This PR adds README.md files to each individual packages in this repo, to improve the user experience of those who will discover Astro Galaxy on npm.

Add README file to individual packages

---

package.json
plop-templates/component/__tests__/index.test.js.hbs
plop-templates/component/index.js.hbs
plop-templates/component/index.story.js.hbs
plopfile.js
yarn.lock

To avoid the hassle of having to create folders and files from scratch when creating new components, we are adding a scaffold generator powered by plop that allows us automate this tedious task.
Just run `yarn create-component` from the root of the project and follow the instructions, given the name of the component and its main HTML tag, such as a `div` or `p`, that will create 3 files inside `packages/components/{{component's name}}`:
- index.js - the component itself;
- index.story.js - the Storybook file;
- `__tests__/index.test.js`: test file for the component;

Scaffold new components with plop

---

.github/CONTRIBUTING.md

This PR adds our contributing guidelines.
To help others people contribute with Astro Galaxy.

Add contributing file

---

.github/CONTRIBUTING.md

Fix Storybook link on CONTRIBUTING file

---

.github/CONTRIBUTING.md

Fix Jest links on Contributing file

---

ADDING_NEW_ICONS.md
CONTRIBUTING.md

As the title implies.
This information was missing from our docs.

Add docs on how to add new icons

---

.github/ISSUE_TEMPLATE/accessibility_issue.md

Add a template for a11y issues.

Add accessibility_issue.md

---

packages/core/src/themes/control.js

This PR reviews and adds design tokens for solid colors and gradients.
To provide the design foundation for Astro Galaxy components.
* Review solid colors tokens
* Add gradient tokens
* Add some missing sizes
* [Card](https://app.clubhouse.io/magnetis/story/23865/revisar-cores-sólidas-e-gradientes-no-galaxy) [ch23865]

Review color and gradient tokens

---

.gitignore
jest.config.js
package.json
packages/docs/gatsby-browser.js
packages/docs/gatsby-config.js
packages/docs/gatsby-node.js
packages/docs/gatsby-ssr.js
packages/docs/package.json
packages/docs/src/components/layout.js
packages/docs/src/pages/404.mdx
packages/docs/src/pages/index.mdx
packages/docs/src/pages/page-2.mdx
packages/docs/yarn.lock

Create a new package for the docs website, using gatsby and mdx
To build: `yarn docs:build`
To develop: `yarn docs:dev`

Create a new package for the docs using gatsby and mdx

---

packages/components/src/Heading/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Heading/__tests__/index.test.js
packages/components/src/Heading/index.js
packages/components/src/Heading/index.story.js
packages/components/src/Text/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Text/__tests__/index.test.js
packages/components/src/Text/index.js
packages/components/src/Text/index.story.js
packages/components/src/index.js
packages/core/src/theme-provider/index.js
packages/core/src/themes/control.js

We did Typography components: Text and Heading.
Hackathon purposes. 
Pair programming @tobiasbu 
Run tests or the storybook (search by Heading and Texts)

[23890] Add typography components

---

.storybook/webpack.config.js
packages/components/src/IconButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconButton/__tests__/index.test.js
packages/components/src/IconButton/index.js
packages/components/src/IconButton/index.story.js
packages/components/src/IconGhostButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconGhostButton/__tests__/index.test.js
packages/components/src/IconGhostButton/index.js
packages/components/src/IconGhostButton/index.story.js
packages/components/src/IconOutlineButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconOutlineButton/__tests__/index.test.js
packages/components/src/IconOutlineButton/index.js
packages/components/src/IconOutlineButton/index.story.js
packages/core/src/themes/control.js

In this PR we are introducing a couple of new buttons:
- IconButton
- IconGhostButton
- IconOutlineButton

Introduce IconButton, IconOutlineButton and IconGhostButton

---

packages/docs/package.json
packages/docs/src/components/Playground.js
packages/docs/src/pages/index.mdx
yarn.lock

Create the Playground component to make the examples interactive

---

packages/docs/src/components/Layout.js
packages/docs/src/components/Menu.js
packages/docs/src/components/Sidebar.js
packages/docs/src/pages/controls-toggles.mdx
packages/docs/src/pages/index.mdx

This __PR__ creates a simple side menu with page title and page headings.
PS: Need to improve accordion on menu Items

Create side menu with page titles and page headings

---

packages/components/src/index.js
packages/docs/src/pages/buttons.mdx

[Docs] - Buttons page

---

packages/docs/src/components/Menu.js

[Docs] - Remove unused Icon import

---

packages/docs/src/components/Layout.js
packages/docs/src/components/Menu.js
packages/docs/src/components/Sidebar.js
packages/docs/src/pages/typography.mdx

After a storm in the galaxy I opening this pull request with Typography page 🔭 
Unfinished challenge from hackathon which desires to be finished.
Writing a simple `.mdx` file.

Typography page

---

packages/docs/src/components/Layout.js
packages/docs/src/components/Playground.js
packages/docs/src/components/PropsTable.js
packages/docs/src/pages/buttons.mdx

This PR updates a bunch of texts regarding the button doc page.

Improve buttons doc page, adding props table and more

---

packages/docs/src/components/Layout.js
packages/docs/src/components/Menu.js
packages/docs/src/components/Sidebar.js

Fix menu style to match the main Astro website;
Implement first fixes in the behaviour.
The side menu didn't match the specs and there were some console JS errors to fix.
Behavior is still not 100% after this PR - the component mounts again everytime an item is clicked, and we'd like to improve that.

Fix menu behavior and style

---

packages/components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Checkbox/__tests__/index.test.js
packages/components/src/Checkbox/index.js
packages/components/src/Checkbox/index.story.js
packages/components/src/Label/index.js
packages/components/src/index.js
packages/docs/src/pages/buttons.mdx
packages/docs/src/pages/controls-toggles.mdx

In this PR we are introducing the Checkbox component, which is a set of components: `Checkbox`, `CheckboxWrapper`, `CheckboxShape` and `Label`.
Please, do check the docs to see how to use them.

Introduce checkbox

---

packages/components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Checkbox/__tests__/index.test.js
packages/components/src/Checkbox/index.js
packages/components/src/Radio/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Radio/__tests__/index.test.js
packages/components/src/Radio/index.js
packages/components/src/Radio/index.story.js
packages/docs/src/pages/controls-toggles.mdx

Adjust existing Radio Buttons code, create tests and reflect them in the documentation.
- Adjust code for radio buttons;
- Create test files;
- Add examples in the documentation (Controls & Toggles page).

Adjust radio buttons and complete tests and documentation

---

packages/core/src/theme-provider/index.js

Have you ever felt nauseous or dizzy while navigating through a website or using an app with too much aggressive animation, or parallax effects? Well, maybe you suffer from a vestibular disorder…
I wrote a blog post about this last year: https://lcs.sh/blog/2018/01/28/reduce-motion/
**THIS ONLY REMOVE FROM PEOPLE THAT ENABLE THE REDUCTION ON THEIR DEVICES.**
To improve Astro's a11y. :)
Using `@media (prefers-reduced-motion: reduce)`.

Add support for reduce motion

---

package.json
packages/components/package.json
packages/core/package.json
packages/docs/package.json
packages/icons/package.json
yarn.lock

This PR bumps all the main dependencies of Astro Galaxy:
- react
- react-dom
- styled-components
- styled-system

Update main dependencies

---

packages/components/src/TextArea/__tests__/__snapshots__/index.test.js.snap
packages/components/src/TextArea/__tests__/index.test.js
packages/components/src/TextArea/index.js
packages/components/src/TextArea/index.story.js
packages/components/src/index.js
packages/docs/src/pages/inputs.mdx

Implement TextArea component
Because.
* Creating TextArea component;
* Implementing tests;
* Adding documentation;

Add TextArea component

---

packages/components/src/Link/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Link/__tests__/index.test.js
packages/components/src/Link/index.js
packages/components/src/Link/index.story.js
packages/components/src/index.js
packages/docs/src/pages/typography.mdx

Create Link component
Why not?
[ch23893]

Implement Link component

---

packages/components/src/IconLinkButton/__tests__/index.test.js
packages/components/src/Tab/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Tab/__tests__/index.test.js
packages/components/src/Tab/index.js
packages/components/src/Tab/index.story.js
packages/components/src/index.js
packages/docs/src/components/Sidebar.js
packages/docs/src/pages/controls-toggles.mdx
plop-templates/component/index.js.hbs

This PR introduces the Tabs component.
Soon this component will receive a facelift and we will need to change it, but until then, here it is.

Introduce Tabs component

---

CHANGELOG.md
packages/components/package.json
packages/core/package.json
packages/docs/package.json
packages/icons/package.json
packages/tokens/README.md
packages/tokens/package.json

As the title implies, this is a alpha version.

Release 1.0.0 alpha.3

---

.eslintrc
jest.setup.js
packages/components/package.json
packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/__tests__/index.test.js
packages/components/src/InputMasked/index.js
packages/components/src/InputMasked/index.story.js
packages/components/src/InputText/__tests__/__snapshots__/index.js.snap
packages/components/src/InputText/__tests__/index.js
packages/components/src/InputText/index.js
packages/components/src/InputText/index.story.js
yarn.lock

This PR adds the masked input component to the project.
Users can be guided by masks to avoid entering incorrect data in the form fields.
* Adds 2 libs to the components subproject: for masks and number formatting
* Creates a wrapper component `InputMasked` to grouping the masking logic
* Adds the global method `mountWithTheme` in the Jest setup file _(existing methods didn't work well with the added libs due to DOM event handling)_
* Add usage examples in the documentation
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/23899/criar-input-com-máscara-no-galaxy) [ch23899]
* [Masking lib](https://www.npmjs.com/package/react-input-mask)
* [Number formatting lib](https://www.npmjs.com/package/react-number-format)

Add masked input component

---

CHANGELOG.md
packages/components/package.json
packages/core/package.json
packages/docs/package.json
packages/icons/package.json
packages/tokens/package.json

In this version, we are adding:
- Introduce MaskedInput component.
- Introduce GhostInput component.
- Update Input component, add large size.
- Introduce Table component.
- Introduce Tabbed component.
- Storybook improvements.
- Introduce ControlInput component.

Release 1.0.0 alpha.4

---

docs/.storybook/main.js
docs/.storybook/manager-head.html
docs/.storybook/preview-head.html
docs/src/08_Tables.stories.mdx
docs/src/components/GitHubButtons.js
package.json
packages/components/src/index.js
yarn.lock

This PR improves a little bit the loading time of Storybook. We done that by:
- Removing unused addon; knobs.
- DNS prefetch unpkg and fonts.gstatic.com.
- Removing GHButtons iframe, using images instead.
The page was taking so long to load.

Improve storybook loading time

---

packages/themes/README.md
packages/themes/package.json
packages/themes/src/index.js
packages/themes/src/mobile-app/index.d.ts
packages/themes/src/mobile-app/index.js
packages/themes/src/web/index.js
packages/tokens/README.md

This PR introduces a new package: `@magnetis/astro-galaxy-themes`. It also introduces a theme designed for Magnetis' mobile app.
Soon we gonna depreciate the themes inside the core package (`@magnetis/astro-galaxy-core`).
Another step to bring Astro Galaxy to our mobile app.

Introduce @magnetis/astro-galaxy-themes

---

RELEASES.md

This PR adds documentation on how to release new versions of Astro Galaxy packages.

Add doc on how to release new versions

---

CHANGELOG.md
packages/components/package.json
packages/core/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

In this version, we are adding `@magnetis/astro-galaxy-themes` package.

Release 1.0.0-alpha.5

---

docs/src/07_ControlsAndToggles.stories.mdx
packages/components/src/InputControl/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputControl/index.js
packages/components/src/InputGhost/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputText/__tests__/__snapshots__/index.js.snap
packages/components/src/InputText/index.js

This PR fixes some visual bugs found in the Design QA.
* Fixes default border color on input components (must be gray, not blue)
* Centralizes the input validation icons
* Replaces input control icons to custom ones for this component
* Fixes the full fill demo slider behavior
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/34534/revisar-componentes-do-astro-galaxy) [34534]

Fix some visual bugs on inputs and control & toggles compoments

---

CHANGELOG.md
packages/components/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

- Deprecate `@magnetis/astro-galaxy-core package`.
- Fix `Tabbed` component icon color.
- Fix `InputControl` component icon position.
- Fix full fill `Slider` component on docs.
- Release 1.0.0.

Release 1.0.0

---

package.json
packages/tokens/package.json
packages/tokens/rollup.config.js

We need to compile tokens, this PR adds support for that.

Add rollup build to tokens package

---

CHANGELOG.md
packages/components/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

- @magnetis/astro-galaxy-tokens has a build process now.
- Add @magnetis/astro-galaxy-tokens as dependency to @magnetis/astro-galaxy-themes.

Release 1.0.2

---

CHANGELOG.md
packages/components/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

- Add new icons; airplane, car, education.

Release 1.1.0

---

CHANGELOG.md
packages/components/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

- Add dynamic extra prop to the Tabbed's Tab component.

Release 1.2.0

---

package.json
packages/components/package.json
packages/components/src/Button/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Button/__tests__/index.test.js
packages/components/src/Checkbox/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Heading/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Heading/__tests__/index.test.js
packages/components/src/IconButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconGhostButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconLinkButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/IconOutlineButton/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputControl/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputFilePreview/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputGhost/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputText/__tests__/__snapshots__/index.js.snap
packages/components/src/InputText/__tests__/index.js
packages/components/src/Link/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Radio/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Slider/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Tab/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Tabbed/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Table/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Text/__tests__/__snapshots__/index.test.js.snap
packages/components/src/TextArea/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Toggle/__tests__/__snapshots__/index.test.js.snap
packages/icons/package.json
packages/themes/package.json
yarn.lock

This __PR__ updates the styled component and all libs necessary to its most new version
As we had some problems with the newest version of styled components at our mobile app project, we decide to update it.

Update styled-component to version 5
