magnetis/astro-galaxy

packages/components/package.json

We are missing `@magnetis/astro-galaxy-core` inside `packages/components`.
We gonna need some tools that are provided by `@magnetis/astro-galaxy-core`.

[CHORE] - Add astro-galaxy-core dependency to components

---

.travis.yml
package.json
packages/components/package.json

The attempt https://github.com/magnetis/astro-galaxy/pull/9 failed.
I figured out that we need to compile the packages first, so Travis can work with the magic links lerna does during `lerna bootstrap` script execution.

[CHORE] - Fix Travis issues regarding lerna linking

---

packages/docs/src/components/icons-collection.js
packages/docs/src/pages/iconography.mdx

This PR adds an initial and simple version of the iconography page.
To display Astro Galaxy icons.
* Add a simple icon list component
* Add an initial iconography page
_PS. This page was created without text styles (typography styles lives in another PR)._

Add initial iconography page

---

package.json
yarn.lock

Updating `eslint-config-react-app` to 5.1.0v
Yesterday we had a problem regarding ESlint in VSCode and during our development environment. This is very annoying bug for VSCode users and can may produce future issues.
yarn add
You can see in the image below (yarn.lock) we had duplicated deps:

Updating ESLint dependency

---

packages/docs/src/components/Layout.js
packages/docs/src/pages/buttons.mdx
packages/docs/src/pages/typography.mdx

Update Typography page copywriting in the documentation;
Change header color to `blackhole`.
This is an improvement to explain usage of our text components.
The header color change was decided to differentiate the main Astro website from the Astro Galaxy.

Update typography page copy and change header color

---

packages/components/src/Button/index.js
packages/docs/src/pages/buttons.mdx

Add a disclaimer about buttons in `<a>` elements usage in the buttons page.

Add docs about buttons in `<a>` elements

---

packages/components/src/Heading/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Heading/index.js
packages/components/src/IconButton/index.js
packages/components/src/IconLinkButton/index.js
packages/components/src/Text/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Text/index.js
packages/core/src/theme-provider/index.js
packages/docs/src/components/Layout.js
packages/docs/src/components/Playground.js
packages/docs/src/components/PropsTable.js
packages/docs/src/pages/buttons.mdx

This PR introduces a bunch of quick fixes and easy wins across the docs pages.
- Update buttons sections titles;
- Fix docs page on mobile web;
- Change playground background-color to enhance its contrast;
Also, a couple of improvements regarding code:
- Export iconlabelMargin helper from `IconButton`, avoiding code duplication;
- Move antialising from Text and Heading to global scope

General quick improvements

---

packages/components/src/Toggle/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Toggle/__tests__/index.test.js
packages/components/src/Toggle/index.js
packages/components/src/Toggle/index.story.js
packages/components/src/index.js
packages/docs/src/components/Menu.js
packages/docs/src/components/Playground.js
packages/docs/src/pages/controls-toggles.mdx

In this PR we are introducing the <q>Toggle</q> component.
It's important to note that we are using a different approach of the [Astro.css' toggle component](https://github.com/magnetis/astro/blob/master/src/css/toggle.css), instead of using an `<input type="checkbox" />`, here we are using a `button` with the `aria-pressed` attribute, and based on that we are styling the toggle accordingly to its specs.
You can find more info about this approach on the Inclusive Components book, or in this link: https://inclusive-components.design/toggle-button/
https://deploy-preview-50--astro-galaxy.netlify.com/controls-toggles/

Introduce Toggle component

---

.storybook/addons.js
package.json
packages/components/src/InputGhost/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputGhost/index.story.js
packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/index.story.js
packages/components/src/InputText/__tests__/__snapshots__/index.js.snap
packages/components/src/InputText/__tests__/index.js
packages/components/src/InputText/index.js
packages/components/src/InputText/index.story.js
yarn.lock

This PR adds a large-sized input variation. This new size will be available to all components based on `InputText`.
The Design team may prefer this alternative for small screens.
* Adds input size variation to the component
* Adds Storybook knobs addon (to allow to change the input size - and other props - in real-time)
* Adds sample on Storybook and test to check the size
* Minor naming adjustments on some component titles on the Storybook menu
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/23904/criar-variações-de-tamanho-dos-inputs) [ch23904]

Add input size feature

---

packages/components/src/Table/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Table/__tests__/index.test.js
packages/components/src/Table/index.js
packages/components/src/Table/index.story.js

This code adds the table component in Astro Galaxy.
For displaying tabular data.
* Add component, with style and test
* Add variant for a dark mode (many of our screens have a dark background)
| Default mode |
| --- |
| <img width="1277" alt="Captura de Tela 2020-03-27 às 18 09 30" src="https://user-images.githubusercontent.com/1002072/77802894-9f49c180-705a-11ea-9cca-c1dfe7583a30.png"> |
| Dark mode |
| --- |
| <img width="1279" alt="Captura de Tela 2020-03-27 às 18 09 52" src="https://user-images.githubusercontent.com/1002072/77802901-a53fa280-705a-11ea-9278-15334d5dabf6.png"> |
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/23905/criar-tabela-padrão-no-galaxy) [ch23905]
* [Astro vanilla ref](http://astro.magnetis.com.br/tables)

Add table component

---

packages/components/src/Tabbed/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Tabbed/__tests__/index.test.js
packages/components/src/Tabbed/index.js
packages/components/src/Tabbed/index.story.js

This PR adds the new tabbed component to Astro Galaxy.
The component [was recently added](https://github.com/magnetis/astro/pull/229), so this code is a port for the Galaxy.
The Design team created a new experience for displaying multi-content grouped by tabs.
* Add tabbed component, script, styles, and test
_PS. the component is close to the story margins, but I intend to open another task to create a global padding and make some cosmetic adjustments to the Storybook._
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/32871/novo-componente-de-tabs) [ch32871]
* [Astro vanilla PR](https://github.com/magnetis/astro/pull/229)

Add tabbed component

---

.storybook/config.js
packages/components/src/Button/index.story.js
packages/components/src/Checkbox/index.story.js
packages/components/src/Heading/index.story.js
packages/components/src/IconButton/index.story.js
packages/components/src/IconGhostButton/index.story.js
packages/components/src/IconLinkButton/index.story.js
packages/components/src/IconOutlineButton/index.story.js
packages/components/src/InputFilePreview/index.story.js
packages/components/src/InputGhost/index.story.js
packages/components/src/InputMasked/index.story.js
packages/components/src/InputText/index.story.js
packages/components/src/Label/index.story.js
packages/components/src/Link/index.story.js
packages/components/src/OutlineButton/index.story.js
packages/components/src/Radio/index.story.js
packages/components/src/Slider/index.story.js
packages/components/src/Tab/index.story.js
packages/components/src/Tabbed/index.story.js
packages/components/src/Table/index.story.js
packages/components/src/Text/index.story.js
packages/components/src/TextArea/index.story.js
packages/components/src/Toggle/index.story.js
packages/icons/index.story.js

This PR organizes the Storybook menu options and adds spaces in the demo area.
* To fit the mental model of the Design team
* To space the components samples in the demo area
and...
[![OCD](https://img.youtube.com/vi/tnzz-eFmKaw/0.jpg)](https://www.youtube.com/watch?v=tnzz-eFmKaw)
([YouTube](https://www.youtube.com/watch?v=tnzz-eFmKaw))
* Create sections on the menu
* Rename and reorganize menu options
* Adjust component demo sections
| Menu tree | |
| --- | --- |
| <img width="205" alt="Captura de Tela 2020-04-02 às 11 13 10" src="https://user-images.githubusercontent.com/1002072/78259416-0dffa280-74d3-11ea-989d-225fc9fabf85.png"> | <img width="201" alt="Captura de Tela 2020-04-02 às 11 13 34" src="https://user-images.githubusercontent.com/1002072/78259429-12c45680-74d3-11ea-9469-a26a86 …

Add Storybook refinements

---

packages/components/src/IconGhostButton/index.js
packages/components/src/InputControl/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputControl/__tests__/index.test.js
packages/components/src/InputControl/index.js
packages/components/src/InputControl/index.story.js
packages/components/src/InputGhost/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/__tests__/__snapshots__/index.test.js.snap
packages/components/src/InputMasked/index.js
packages/components/src/InputText/__tests__/__snapshots__/index.js.snap
packages/components/src/InputText/index.js
packages/core/src/themes/control.js

This PR adds the Input control component to the Galaxy.
To allow users to increment or decrement numeric fields.
* Add control input component, styles, markup, and test
* Perform minor optimizations in other components to support control input requisites 
_As other Galaxy components, this component has no state logic inside it (dumb type). I put a sample state usage in the storybook demo in order to the component to work._
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/23902/criar-input-com-controles-no-galaxy)

Add control input component

---

.storybook/webpack.config.js
docs/04_Iconography.stories.mdx
docs/components/IconsCollection.js

This PR adds the complete icons page to the new Storybook docs.
It also adds support to `@magnetis/astro-galaxy-tokens` on Storybook.
For Astro Galaxy devs to have a reference of Input components usage.

Add icons page

---

docs/02_Colors.stories.mdx
docs/components/ColorsCollection.js

This PR adds the complete colors and gradients page to the new Storybook docs.
For Astro Galaxy devs to have a reference of Input components usage.

Add colors and gradients page

---

docs/.storybook/babel.config.js
docs/.storybook/preview-head.html
docs/.storybook/preview.js
docs/.storybook/webpack.config.js
docs/src/07_ControlsAndToggles.stories.mdx
docs/src/08_Tables.stories.mdx
docs/src/components/Card.js
docs/src/components/PreviewGrid.js
package.json
yarn.lock

This PR makes some style adjustments to address some layout bugs in small screen resolutions.
So that Astro users can consult the documentation on smaller screens.
* Adjusts paddings and margins on some elements
* Handles the alignment of the `<PreviewGrid>` component items on small screens
* Fixes H1 spacing on small screens
This PR also:
* Fixes some props and imports to eliminate console error messages
* Tries to improve the build and size of the bundle with a babel `lodash` plugin and some Webpack parameters
| | | |
| --- | --- | --- |
| <img width="361" alt="Captura de Tela 2020-04-27 às 14 13 39" src="https://user-images.githubusercontent.com/1002072/80401689-25903800-8893-11ea-8861-daf975e24508.png"> | <img width="358" alt="Captura de Tela 2020-04-27 às 14 14 02" …

Fix small screens layout issues

---

docs/.storybook/manager-head.html
docs/src/01_Home.stories.mdx
docs/src/02_Colors.stories.mdx
docs/src/03_Typography.stories.mdx
docs/src/04_Iconography.stories.mdx
docs/src/05_Buttons.stories.mdx
docs/src/06_Inputs.stories.mdx
docs/src/07_ControlsAndToggles.stories.mdx
docs/src/08_Tables.stories.mdx

This PR fixes the title of the pages, which were created with an additional backslash.
OCD. 😊 
* Removes backslash from titles
* Adjusts styles to the changed menu structure
* [Clubhouse card](https://app.clubhouse.io/magnetis/story/36721/ajustar-títulos-das-páginas-no-storybook) [ch36721]

Fix page titles

---

docs/src/components/IconsCollection.js
packages/components/src/Tabbed/__tests__/__snapshots__/index.test.js.snap
packages/components/src/Tabbed/index.js

This PR fix some issues reported during QA.
- Tabbed icons colors;
- Icons docs alignment;
**Normal state should be `moon500`.**
**Hover should be `moon300`.**
**Icons docs alignments.**

Fix Tabbed icons and doc icons

---

packages/themes/package.json

This PR adds `@magnetis/astro-galaxy-tokens` as a dependency for `@magnetis/astro-galaxy-themes` package.

Add galaxy-tokens dependency to galaxy-themes

---

CHANGELOG.md
packages/components/package.json
packages/icons/package.json
packages/themes/package.json
packages/tokens/package.json

- Correct Tabbed component export.
- Change the Text component to display the secondary font as default.
- Add more values for spacing on web theme (margin, padding, etc.).

Release 1.1.1

---

packages/components/src/Tabbed/index.js

This huge PR 😊 adds additional parameters to the `<Tab>` item of the `<Tabbed>` component.
This was necessary to, for example, add `onClick` handlers for analytics tracking.
I'll let you guess. 😆 
No visual perk this time.

Add extra params to the Tabbed's Tab
